#!/bin/bash

set -e

INFILE=$1
EXTPREFIX=$2

CCD=({01,02,03,04,05,06,07,08,09,10,11,12})
# EXTNUMBER=0

for k in 0 1 2 3 4 5 6 7 8 9 10 11; do {

  EXTNAME=$EXTPREFIX${CCD[${k}]}
  fextract infile=$INFILE"["$EXTNAME"]" outfile=$EXTNAME.fits clobber=yes

};
done
#echo "Extracted $EXTPREFIX extensions from $INFILE"
