#!/bin/bash
# change one line in XMM badpix extention

#file="$1"
#row="$2"
#rawx="$3"
#rawy="$4"
#type="$5"
#yextent="$6"
#badflag="$7"

fpartab $3 $1 RAWX $2
fpartab $4 $1 RAWY $2
fpartab $5 $1 TYPE $2
fpartab $6 $1 YEXTENT $2
fpartab $7 $1 BADFLAG $2
