#!/bin/bash

# After the complete installation, put this file in your home directory and make it executable (chmod u=rwx iraf). The command "sh iraf" will then launch a complete IRAF session containing DS9, xgterm and ecl, based in ~/IRAF.

# Please send questions or comments to: rubab@astro.columbia.edu

cd ~/IRAF ; ds9 ; xterm -title "Image Reduction and Analysis Facility (IRAF)" -e "ecl" &
