 NGC1316
DefaultName    PP
Duration    030000
RA2000    032241.7000
DEC2000    -371230.000
TypeOfEpoch    C
ReferencePointing     
BandCode(1)    P
BandCode(2)    P
BandCode(3)    P
BandCode(4)    P
BandwidthCode(1)    4
BandwidthCode(2)    4
BandwidthCode(3)    4
BandwidthCode(4)    4
FEBandpassFilterCode(1)    1
FEBandpassFilterCode(2)    1
FEBandpassFilterCode(3)    1
FEBandpassFilterCode(4)    1
SynthCode    S
SynthFreqVel(1)    F
SynthFreqVel(2)    F
SynthFreqVel(3)    F
SynthFreqVel(4)    F
SynthFreqType    T
SkyFrequency(1)    327.500000
SkyFrequency(2)    321.56250
SkyFrequency(3)    327.500000
SkyFrequency(4)    321.56250
ObservingMode      
CorrelatorMode    4
APMode    H
IntegrationTime    10
 0409-179
Name    0409-179
NRAOCalibrator    YES
RA2000*   040906.7000
DEC2000*   -175710.039
TypeOfEpoch*   C
CalCode*   T
SynthFreqType    T
 NGC1600
DefaultName    PP
Duration    030000
RA2000    043139.8000
DEC2000    -050510.000
TypeOfEpoch    C
ReferencePointing     
BandCode(1)    P
BandCode(2)    P
BandCode(3)    P
BandCode(4)    P
BandwidthCode(1)    4
BandwidthCode(2)    4
BandwidthCode(3)    4
BandwidthCode(4)    4
FEBandpassFilterCode(1)    1
FEBandpassFilterCode(2)    1
FEBandpassFilterCode(3)    1
FEBandpassFilterCode(4)    1
SynthCode    S
SynthFreqVel(1)    F
SynthFreqVel(2)    F
SynthFreqVel(3)    F
SynthFreqVel(4)    F
SynthFreqType    T
SkyFrequency(1)    327.500000
SkyFrequency(2)    321.56250
SkyFrequency(3)    327.500000
SkyFrequency(4)    321.56250
ObservingMode      
CorrelatorMode    4
APMode    H
IntegrationTime    10
 NGC3077
DefaultName    PP
Duration    030000
RA2000    100319.1000
DEC2000    684402.000
TypeOfEpoch    C
ReferencePointing     
BandCode(1)    P
BandCode(2)    P
BandCode(3)    P
BandCode(4)    P
BandwidthCode(1)    4
BandwidthCode(2)    4
BandwidthCode(3)    4
BandwidthCode(4)    4
FEBandpassFilterCode(1)    1
FEBandpassFilterCode(2)    1
FEBandpassFilterCode(3)    1
FEBandpassFilterCode(4)    1
SynthCode    S
SynthFreqVel(1)    F
SynthFreqVel(2)    F
SynthFreqVel(3)    F
SynthFreqVel(4)    F
SynthFreqType    T
SkyFrequency(1)    327.500000
SkyFrequency(2)    321.56250
SkyFrequency(3)    327.500000
SkyFrequency(4)    321.56250
ObservingMode      
CorrelatorMode    4
APMode    H
IntegrationTime    10
 NGC3608
DefaultName    PP
Duration    030000
RA2000    111658.9000
DEC2000    180855.000
TypeOfEpoch    C
ReferencePointing     
BandCode(1)    P
BandCode(2)    P
BandCode(3)    P
BandCode(4)    P
BandwidthCode(1)    4
BandwidthCode(2)    4
BandwidthCode(3)    4
BandwidthCode(4)    4
FEBandpassFilterCode(1)    1
FEBandpassFilterCode(2)    1
FEBandpassFilterCode(3)    1
FEBandpassFilterCode(4)    1
SynthCode    S
SynthFreqVel(1)    F
SynthFreqVel(2)    F
SynthFreqVel(3)    F
SynthFreqVel(4)    F
SynthFreqType    T
SkyFrequency(1)    327.500000
SkyFrequency(2)    321.56250
SkyFrequency(3)    327.500000
SkyFrequency(4)    321.56250
ObservingMode      
CorrelatorMode    4
APMode    H
IntegrationTime    10
 NGC4261
DefaultName    PP
Duration    030000
RA2000    121923.2000
DEC2000    054931.000
TypeOfEpoch    C
ReferencePointing     
BandCode(1)    P
BandCode(2)    P
BandCode(3)    P
BandCode(4)    P
BandwidthCode(1)    4
BandwidthCode(2)    4
BandwidthCode(3)    4
BandwidthCode(4)    4
FEBandpassFilterCode(1)    1
FEBandpassFilterCode(2)    1
FEBandpassFilterCode(3)    1
FEBandpassFilterCode(4)    1
SynthCode    S
SynthFreqVel(1)    F
SynthFreqVel(2)    F
SynthFreqVel(3)    F
SynthFreqVel(4)    F
SynthFreqType    T
SkyFrequency(1)    327.500000
SkyFrequency(2)    321.56250
SkyFrequency(3)    327.500000
SkyFrequency(4)    321.56250
ObservingMode      
CorrelatorMode    4
APMode    H
IntegrationTime    10
 NGC4374
DefaultName    PP
Duration    030000
RA2000    122503.7000
DEC2000    125313.000
TypeOfEpoch    C
ReferencePointing     
BandCode(1)    P
BandCode(2)    P
BandCode(3)    P
BandCode(4)    P
BandwidthCode(1)    4
BandwidthCode(2)    4
BandwidthCode(3)    4
BandwidthCode(4)    4
FEBandpassFilterCode(1)    1
FEBandpassFilterCode(2)    1
FEBandpassFilterCode(3)    1
FEBandpassFilterCode(4)    1
SynthCode    S
SynthFreqVel(1)    F
SynthFreqVel(2)    F
SynthFreqVel(3)    F
SynthFreqVel(4)    F
SynthFreqType    T
SkyFrequency(1)    327.500000
SkyFrequency(2)    321.56250
SkyFrequency(3)    327.500000
SkyFrequency(4)    321.56250
ObservingMode      
CorrelatorMode    4
APMode    H
IntegrationTime    10
 NGC4472
DefaultName    PP
Duration    030000
RA2000    122946.7000
DEC2000    080002.000
TypeOfEpoch    C
ReferencePointing     
BandCode(1)    P
BandCode(2)    P
BandCode(3)    P
BandCode(4)    P
BandwidthCode(1)    4
BandwidthCode(2)    4
BandwidthCode(3)    4
BandwidthCode(4)    4
FEBandpassFilterCode(1)    1
FEBandpassFilterCode(2)    1
FEBandpassFilterCode(3)    1
FEBandpassFilterCode(4)    1
SynthCode    S
SynthFreqVel(1)    F
SynthFreqVel(2)    F
SynthFreqVel(3)    F
SynthFreqVel(4)    F
SynthFreqType    T
SkyFrequency(1)    327.500000
SkyFrequency(2)    321.56250
SkyFrequency(3)    327.500000
SkyFrequency(4)    321.56250
ObservingMode      
CorrelatorMode    4
APMode    H
IntegrationTime    10
 NGC4552
DefaultName    PP
Duration    030000
RA2000    123539.8000
DEC2000    123323.000
TypeOfEpoch    C
ReferencePointing     
BandCode(1)    P
BandCode(2)    P
BandCode(3)    P
BandCode(4)    P
BandwidthCode(1)    4
BandwidthCode(2)    4
BandwidthCode(3)    4
BandwidthCode(4)    4
FEBandpassFilterCode(1)    1
FEBandpassFilterCode(2)    1
FEBandpassFilterCode(3)    1
FEBandpassFilterCode(4)    1
SynthCode    S
SynthFreqVel(1)    F
SynthFreqVel(2)    F
SynthFreqVel(3)    F
SynthFreqVel(4)    F
SynthFreqType    T
SkyFrequency(1)    327.500000
SkyFrequency(2)    321.56250
SkyFrequency(3)    327.500000
SkyFrequency(4)    321.56250
ObservingMode      
CorrelatorMode    4
APMode    H
IntegrationTime    10
 NGC4782
DefaultName    PP
Duration    030000
RA2000    125435.7000
DEC2000    -123407.000
TypeOfEpoch    C
ReferencePointing     
BandCode(1)    P
BandCode(2)    P
BandCode(3)    P
BandCode(4)    P
BandwidthCode(1)    4
BandwidthCode(2)    4
BandwidthCode(3)    4
BandwidthCode(4)    4
FEBandpassFilterCode(1)    1
FEBandpassFilterCode(2)    1
FEBandpassFilterCode(3)    1
FEBandpassFilterCode(4)    1
SynthCode    S
SynthFreqVel(1)    F
SynthFreqVel(2)    F
SynthFreqVel(3)    F
SynthFreqVel(4)    F
SynthFreqType    T
SkyFrequency(1)    327.500000
SkyFrequency(2)    321.56250
SkyFrequency(3)    327.500000
SkyFrequency(4)    321.56250
ObservingMode      
CorrelatorMode    4
APMode    H
IntegrationTime    10
 IC4296
DefaultName    PP
Duration    030000
RA2000    133639.0000
DEC2000    -335757.000
TypeOfEpoch    C
ReferencePointing     
BandCode(1)    P
BandCode(2)    P
BandCode(3)    P
BandCode(4)    P
BandwidthCode(1)    4
BandwidthCode(2)    4
BandwidthCode(3)    4
BandwidthCode(4)    4
FEBandpassFilterCode(1)    1
FEBandpassFilterCode(2)    1
FEBandpassFilterCode(3)    1
FEBandpassFilterCode(4)    1
SynthCode    S
SynthFreqVel(1)    F
SynthFreqVel(2)    F
SynthFreqVel(3)    F
SynthFreqVel(4)    F
SynthFreqType    T
SkyFrequency(1)    327.500000
SkyFrequency(2)    321.56250
SkyFrequency(3)    327.500000
SkyFrequency(4)    321.56250
ObservingMode      
CorrelatorMode    4
APMode    H
IntegrationTime    10
 NGC5252
DefaultName    PP
Duration    030000
RA2000    133815.9000
DEC2000    043233.000
TypeOfEpoch    C
ReferencePointing     
BandCode(1)    P
BandCode(2)    P
BandCode(3)    P
BandCode(4)    P
BandwidthCode(1)    4
BandwidthCode(2)    4
BandwidthCode(3)    4
BandwidthCode(4)    4
FEBandpassFilterCode(1)    1
FEBandpassFilterCode(2)    1
FEBandpassFilterCode(3)    1
FEBandpassFilterCode(4)    1
SynthCode    S
SynthFreqVel(1)    F
SynthFreqVel(2)    F
SynthFreqVel(3)    F
SynthFreqVel(4)    F
SynthFreqType    T
SkyFrequency(1)    327.500000
SkyFrequency(2)    321.56250
SkyFrequency(3)    327.500000
SkyFrequency(4)    321.56250
ObservingMode      
CorrelatorMode    4
APMode    H
IntegrationTime    10
 NGC5253
DefaultName    PP
Duration    030000
RA2000    133955.9000
DEC2000    -313824.000
TypeOfEpoch    C
ReferencePointing     
BandCode(1)    P
BandCode(2)    P
BandCode(3)    P
BandCode(4)    P
BandwidthCode(1)    4
BandwidthCode(2)    4
BandwidthCode(3)    4
BandwidthCode(4)    4
FEBandpassFilterCode(1)    1
FEBandpassFilterCode(2)    1
FEBandpassFilterCode(3)    1
FEBandpassFilterCode(4)    1
SynthCode    S
SynthFreqVel(1)    F
SynthFreqVel(2)    F
SynthFreqVel(3)    F
SynthFreqVel(4)    F
SynthFreqType    T
SkyFrequency(1)    327.500000
SkyFrequency(2)    321.56250
SkyFrequency(3)    327.500000
SkyFrequency(4)    321.56250
ObservingMode      
CorrelatorMode    4
APMode    H
IntegrationTime    10
 NGC6338
DefaultName    PP
Duration    030000
RA2000    171523.0000
DEC2000    572440.000
TypeOfEpoch    C
ReferencePointing     
BandCode(1)    P
BandCode(2)    P
BandCode(3)    P
BandCode(4)    P
BandwidthCode(1)    4
BandwidthCode(2)    4
BandwidthCode(3)    4
BandwidthCode(4)    4
FEBandpassFilterCode(1)    1
FEBandpassFilterCode(2)    1
FEBandpassFilterCode(3)    1
FEBandpassFilterCode(4)    1
SynthCode    S
SynthFreqVel(1)    F
SynthFreqVel(2)    F
SynthFreqVel(3)    F
SynthFreqVel(4)    F
SynthFreqType    T
SkyFrequency(1)    327.500000
SkyFrequency(2)    321.56250
SkyFrequency(3)    327.500000
SkyFrequency(4)    321.56250
ObservingMode      
CorrelatorMode    4
APMode    H
IntegrationTime    10
 0521+166
Name    0521+166
NRAOCalibrator    YES
RA2000*   052109.886021
DEC2000*   163822.051220
TypeOfEpoch*   C
CalCode*   A
SynthFreqType    T
