 NGC1600
DefaultName    PP
Duration    030000
RA2000    043139.8000
DEC2000    -050510.000
TypeOfEpoch    C
ReferencePointing     
BandCode(1)    P
BandCode(2)    P
BandCode(3)    P
BandCode(4)    P
BandwidthCode(1)    4
BandwidthCode(2)    4
BandwidthCode(3)    4
BandwidthCode(4)    4
FEBandpassFilterCode(1)    1
FEBandpassFilterCode(2)    1
FEBandpassFilterCode(3)    1
FEBandpassFilterCode(4)    1
SynthCode    S
SynthFreqVel(1)    F
SynthFreqVel(2)    F
SynthFreqVel(3)    F
SynthFreqVel(4)    F
SynthFreqType    T
SkyFrequency(1)    327.500000
SkyFrequency(2)    321.56250
SkyFrequency(3)    327.500000
SkyFrequency(4)    321.56250
ObservingMode      
CorrelatorMode    4
APMode    H
IntegrationTime    10
 0409-179
DefaultName    PP
Name    0409-179
NRAOCalibrator    YES
CalibratorFlux      6.00
RA2000*   040906.7000
DEC2000*   -175710.039
TypeOfEpoch*   C
CalCode*   T
ReferencePointing     
BandCode(1)    P
BandCode(2)    P
BandCode(3)    P
BandCode(4)    P
BandwidthCode(1)    4
BandwidthCode(2)    4
BandwidthCode(3)    4
BandwidthCode(4)    4
FEBandpassFilterCode(1)    1
FEBandpassFilterCode(2)    1
FEBandpassFilterCode(3)    1
FEBandpassFilterCode(4)    1
SynthCode    S
SynthFreqVel(1)    F
SynthFreqVel(2)    F
SynthFreqVel(3)    F
SynthFreqVel(4)    F
SynthFreqType    T
SkyFrequency(1)    327.500000
SkyFrequency(2)    321.56250
SkyFrequency(3)    327.500000
SkyFrequency(4)    321.56250
ObservingMode      
CorrelatorMode    4
APMode    H
IntegrationTime    10
 NGC3077
DefaultName    PP
Duration    030000
RA2000    100319.1000
DEC2000    684402.000
TypeOfEpoch    C
ReferencePointing     
BandCode(1)    P
BandCode(2)    P
BandCode(3)    P
BandCode(4)    P
BandwidthCode(1)    4
BandwidthCode(2)    4
BandwidthCode(3)    4
BandwidthCode(4)    4
FEBandpassFilterCode(1)    1
FEBandpassFilterCode(2)    1
FEBandpassFilterCode(3)    1
FEBandpassFilterCode(4)    1
SynthCode    S
SynthFreqVel(1)    F
SynthFreqVel(2)    F
SynthFreqVel(3)    F
SynthFreqVel(4)    F
SynthFreqType    T
SkyFrequency(1)    327.500000
SkyFrequency(2)    321.56250
SkyFrequency(3)    327.500000
SkyFrequency(4)    321.56250
ObservingMode      
CorrelatorMode    4
APMode    H
IntegrationTime    10
 1206+642
DefaultName    PP
Name    1206+642
NRAOCalibrator    YES
CalibratorFlux     10.00
RA2000*   120624.6868
DEC2000*   641337.340
TypeOfEpoch*   C
CalCode*   T
ReferencePointing     
BandCode(1)    P
BandCode(2)    P
BandCode(3)    P
BandCode(4)    P
BandwidthCode(1)    4
BandwidthCode(2)    4
BandwidthCode(3)    4
BandwidthCode(4)    4
FEBandpassFilterCode(1)    1
FEBandpassFilterCode(2)    1
FEBandpassFilterCode(3)    1
FEBandpassFilterCode(4)    1
SynthCode    S
SynthFreqVel(1)    F
SynthFreqVel(2)    F
SynthFreqVel(3)    F
SynthFreqVel(4)    F
SynthFreqType    T
SkyFrequency(1)    327.500000
SkyFrequency(2)    321.56250
SkyFrequency(3)    327.500000
SkyFrequency(4)    321.56250
ObservingMode      
CorrelatorMode    4
APMode    H
IntegrationTime    10
 NGC3608
DefaultName    PP
Duration    030000
RA2000    111658.9000
DEC2000    180855.000
TypeOfEpoch    C
ReferencePointing     
BandCode(1)    P
BandCode(2)    P
BandCode(3)    P
BandCode(4)    P
BandwidthCode(1)    4
BandwidthCode(2)    4
BandwidthCode(3)    4
BandwidthCode(4)    4
FEBandpassFilterCode(1)    1
FEBandpassFilterCode(2)    1
FEBandpassFilterCode(3)    1
FEBandpassFilterCode(4)    1
SynthCode    S
SynthFreqVel(1)    F
SynthFreqVel(2)    F
SynthFreqVel(3)    F
SynthFreqVel(4)    F
SynthFreqType    T
SkyFrequency(1)    327.500000
SkyFrequency(2)    321.56250
SkyFrequency(3)    327.500000
SkyFrequency(4)    321.56250
ObservingMode      
CorrelatorMode    4
APMode    H
IntegrationTime    10
 1021+219
Name    1021+219
NRAOCalibrator    YES
RA2000*   102154.5289
DEC2000*   215930.440
TypeOfEpoch*   C
CalCode*   T
SynthFreqType    T
 NGC4374
DefaultName    PP
Duration    030000
RA2000    122503.7000
DEC2000    125313.000
TypeOfEpoch    C
ReferencePointing     
BandCode(1)    P
BandCode(2)    P
BandCode(3)    P
BandCode(4)    P
BandwidthCode(1)    4
BandwidthCode(2)    4
BandwidthCode(3)    4
BandwidthCode(4)    4
FEBandpassFilterCode(1)    1
FEBandpassFilterCode(2)    1
FEBandpassFilterCode(3)    1
FEBandpassFilterCode(4)    1
SynthCode    S
SynthFreqVel(1)    F
SynthFreqVel(2)    F
SynthFreqVel(3)    F
SynthFreqVel(4)    F
SynthFreqType    T
SkyFrequency(1)    327.500000
SkyFrequency(2)    321.56250
SkyFrequency(3)    327.500000
SkyFrequency(4)    321.56250
ObservingMode      
CorrelatorMode    4
APMode    H
IntegrationTime    10
 1330+251
Name    1330+251
NRAOCalibrator    YES
RA2000*   133037.6892
DEC2000*   250910.978
TypeOfEpoch*   C
CalCode*   C
SynthFreqType    T
 NGC6338
DefaultName    PP
Duration    030000
RA2000    171523.0000
DEC2000    572440.000
TypeOfEpoch    C
ReferencePointing     
BandCode(1)    P
BandCode(2)    P
BandCode(3)    P
BandCode(4)    P
BandwidthCode(1)    4
BandwidthCode(2)    4
BandwidthCode(3)    4
BandwidthCode(4)    4
FEBandpassFilterCode(1)    1
FEBandpassFilterCode(2)    1
FEBandpassFilterCode(3)    1
FEBandpassFilterCode(4)    1
SynthCode    S
SynthFreqVel(1)    F
SynthFreqVel(2)    F
SynthFreqVel(3)    F
SynthFreqVel(4)    F
SynthFreqType    T
SkyFrequency(1)    327.500000
SkyFrequency(2)    321.56250
SkyFrequency(3)    327.500000
SkyFrequency(4)    321.56250
ObservingMode      
CorrelatorMode    4
APMode    H
IntegrationTime    10
 1459+716
DefaultName    PP
Name    1459+716
NRAOCalibrator    YES
CalibratorFlux     19.00
RA2000*   145907.583867
DEC2000*   714019.867740
TypeOfEpoch*   C
CalCode*   A
ReferencePointing     
BandCode(1)    P
BandCode(2)    P
BandCode(3)    P
BandCode(4)    P
BandwidthCode(1)    4
BandwidthCode(2)    4
BandwidthCode(3)    4
BandwidthCode(4)    4
FEBandpassFilterCode(1)    1
FEBandpassFilterCode(2)    1
FEBandpassFilterCode(3)    1
FEBandpassFilterCode(4)    1
SynthCode    S
SynthFreqVel(1)    F
SynthFreqVel(2)    F
SynthFreqVel(3)    F
SynthFreqVel(4)    F
SkyFrequency(1)    327.500000
SkyFrequency(2)    321.56250
SkyFrequency(3)    327.500000
SkyFrequency(4)    321.56250
ObservingMode      
CorrelatorMode    4
APMode    H
IntegrationTime    10
 0521+166
DefaultName    PP
Duration    000500
Name    0521+166
NRAOCalibrator    YES
CalibratorFlux    17.50
RA2000*   052109.886021
DEC2000*   163822.051220
TypeOfEpoch*   C
CalCode*   A
ReferencePointing     
BandCode(1)    P
BandCode(2)    P
BandCode(3)    P
BandCode(4)    P
BandwidthCode(1)    4
BandwidthCode(2)    4
BandwidthCode(3)    4
BandwidthCode(4)    4
FEBandpassFilterCode(1)    1
FEBandpassFilterCode(2)    1
FEBandpassFilterCode(3)    1
FEBandpassFilterCode(4)    1
SynthCode    S
SynthFreqVel(1)    F
SynthFreqVel(2)    F
SynthFreqVel(3)    F
SynthFreqVel(4)    F
SynthFreqType    T
SkyFrequency(1)    327.500000
SkyFrequency(2)    321.56250
SkyFrequency(3)    327.500000
SkyFrequency(4)    321.56250
ObservingMode      
CorrelatorMode    4
APMode    H
IntegrationTime    10
