 0521+166
DefaultName    PP
Name    0521+166
NRAOCalibrator    YES
CalibratorFlux     17.50
RA2000*   052109.886021
DEC2000*   163822.051220
TypeOfEpoch*   C
CalCode*   A
ReferencePointing     
BandCode(1)    P
BandCode(2)    P
BandCode(3)    P
BandCode(4)    P
BandwidthCode(1)    4
BandwidthCode(2)    4
BandwidthCode(3)    4
BandwidthCode(4)    4
FEBandpassFilterCode(1)    1
FEBandpassFilterCode(2)    1
FEBandpassFilterCode(3)    1
FEBandpassFilterCode(4)    1
SynthCode    S
SynthFreqVel(1)    F
SynthFreqVel(2)    F
SynthFreqVel(3)    F
SynthFreqVel(4)    F
SynthFreqType    T
SkyFrequency(1)    327.500000
SkyFrequency(2)    321.56250
SkyFrequency(3)    327.500000
SkyFrequency(4)    321.56250
ObservingMode      
CorrelatorMode    4
APMode    H
IntegrationTime    10
 NGC4552
DefaultName    PP
Duration    030000
RA2000    123539.8000
DEC2000    123323.000
TypeOfEpoch    C
ReferencePointing     
BandCode(1)    P
BandCode(2)    P
BandCode(3)    P
BandCode(4)    P
BandwidthCode(1)    4
BandwidthCode(2)    4
BandwidthCode(3)    4
BandwidthCode(4)    4
FEBandpassFilterCode(1)    1
FEBandpassFilterCode(2)    1
FEBandpassFilterCode(3)    1
FEBandpassFilterCode(4)    1
SynthCode    S
SynthFreqVel(1)    F
SynthFreqVel(2)    F
SynthFreqVel(3)    F
SynthFreqVel(4)    F
SynthFreqType    T
SkyFrequency(1)    327.500000
SkyFrequency(2)    321.56250
SkyFrequency(3)    327.500000
SkyFrequency(4)    321.56250
ObservingMode      
CorrelatorMode    4
APMode    H
IntegrationTime    10
 1330+251
DefaultName    PP
Name    1330+251
NRAOCalibrator    YES
CalibratorFlux     15.00
RA2000*   133037.6892
DEC2000*   250910.978
TypeOfEpoch*   C
CalCode*   C
ReferencePointing     
BandCode(1)    P
BandCode(2)    P
BandCode(3)    P
BandCode(4)    P
BandwidthCode(1)    4
BandwidthCode(2)    4
BandwidthCode(3)    4
BandwidthCode(4)    4
FEBandpassFilterCode(1)    1
FEBandpassFilterCode(2)    1
FEBandpassFilterCode(3)    1
FEBandpassFilterCode(4)    1
SynthCode    S
SynthFreqVel(1)    F
SynthFreqVel(2)    F
SynthFreqVel(3)    F
SynthFreqVel(4)    F
SynthFreqType    T
SkyFrequency(1)    327.500000
SkyFrequency(2)    321.56250
SkyFrequency(3)    327.500000
SkyFrequency(4)    321.56250
ObservingMode      
CorrelatorMode    4
APMode    H
IntegrationTime    10
