 1331+305
DefaultName    PP
Name    1331+305
NRAOCalibrator    YES
CalibratorFlux    26.00
RA2000*   133108.287984
DEC2000*   303032.958850
TypeOfEpoch*   C
CalCode*   A
ReferencePointing     
BandCode(1)    P
BandCode(2)    P
BandCode(3)    P
BandCode(4)    P
BandwidthCode(1)    4
BandwidthCode(2)    4
BandwidthCode(3)    4
BandwidthCode(4)    4
FEBandpassFilterCode(1)    1
FEBandpassFilterCode(2)    1
FEBandpassFilterCode(3)    1
FEBandpassFilterCode(4)    1
SynthCode    S
SynthFreqVel(1)    F
SynthFreqVel(2)    F
SynthFreqVel(3)    F
SynthFreqVel(4)    F
SynthFreqType    T
SkyFrequency(1)    327.500000
SkyFrequency(2)    321.56250
SkyFrequency(3)    327.500000
SkyFrequency(4)    321.56250
ObservingMode      
CorrelatorMode    4
APMode    H
IntegrationTime    10
 NGC4261
DefaultName    PP
Duration    030000
RA2000    121923.2000
DEC2000    054931.000
TypeOfEpoch    C
ReferencePointing     
BandCode(1)    P
BandCode(2)    P
BandCode(3)    P
BandCode(4)    P
BandwidthCode(1)    4
BandwidthCode(2)    4
BandwidthCode(3)    4
BandwidthCode(4)    4
FEBandpassFilterCode(1)    1
FEBandpassFilterCode(2)    1
FEBandpassFilterCode(3)    1
FEBandpassFilterCode(4)    1
SynthCode    S
SynthFreqVel(1)    F
SynthFreqVel(2)    F
SynthFreqVel(3)    F
SynthFreqVel(4)    F
SynthFreqType    T
SkyFrequency(1)    327.500000
SkyFrequency(2)    321.56250
SkyFrequency(3)    327.500000
SkyFrequency(4)    321.56250
ObservingMode      
CorrelatorMode    4
APMode    H
IntegrationTime    10
 NGC4472
DefaultName    PP
Duration    030000
RA2000    122946.7000
DEC2000    080002.000
TypeOfEpoch    C
ReferencePointing     
BandCode(1)    P
BandCode(2)    P
BandCode(3)    P
BandCode(4)    P
BandwidthCode(1)    4
BandwidthCode(2)    4
BandwidthCode(3)    4
BandwidthCode(4)    4
FEBandpassFilterCode(1)    1
FEBandpassFilterCode(2)    1
FEBandpassFilterCode(3)    1
FEBandpassFilterCode(4)    1
SynthCode    S
SynthFreqVel(1)    F
SynthFreqVel(2)    F
SynthFreqVel(3)    F
SynthFreqVel(4)    F
SynthFreqType    T
SkyFrequency(1)    327.500000
SkyFrequency(2)    321.56250
SkyFrequency(3)    327.500000
SkyFrequency(4)    321.56250
ObservingMode      
CorrelatorMode    4
APMode    H
IntegrationTime    10
 1119-030
DefaultName    PP
Name    1119-030
NRAOCalibrator    YES
CalibratorFlux    10.00
RA2000*   111925.3000
DEC2000*   -030251.320
TypeOfEpoch*   C
CalCode*   T
ReferencePointing     
BandCode(1)    P
BandCode(2)    P
BandCode(3)    P
BandCode(4)    P
BandwidthCode(1)    4
BandwidthCode(2)    4
BandwidthCode(3)    4
BandwidthCode(4)    4
FEBandpassFilterCode(1)    1
FEBandpassFilterCode(2)    1
FEBandpassFilterCode(3)    1
FEBandpassFilterCode(4)    1
SynthCode    S
SynthFreqVel(1)    F
SynthFreqVel(2)    F
SynthFreqVel(3)    F
SynthFreqVel(4)    F
SynthFreqType    T
SkyFrequency(1)    327.500000
SkyFrequency(2)    321.56250
SkyFrequency(3)    327.500000
SkyFrequency(4)    321.56250
ObservingMode      
CorrelatorMode    4
APMode    H
IntegrationTime    10
