;DEVICE, RETAIN=2
;DEVICE, DECOMPOSED=0
;COLOR_MANAGER, NUM_RESERVED=9
;WIDGET_CONTROL, DEFAULT_FONT='5x8'
;ASTROLIB
!FANCY    = 4
!LINETYPE = 0
!P.FONT   = 0
!X.THICK  = 3
!Y.THICK  = 3
!Z.THICK  = 3
