cp ../radiofit.eps .
cp ../radiofit_lobes.eps .
cp ../i09.ps .
cp ../unsharp.ps .
cp ../resid_betamod.ps .
cp ../resid_freemod.ps .
cp ../resid_fixedmod.ps .
cp ../resid_beta.ps .
cp ../resid_free.ps .
cp ../resid_fixed.ps .
cp ../ellpa.ps .
cp ../cavs.ps .
cp ../resid_cones.ps .
cp ../iras09_nhfro.eps .
cp ../tsyn_k.eps .
cp ../tsyn_k_lobe.eps .
cp ../hardness.ps .
cp ../nuc.ps .
cp ../exspec.ps .
cp ../opt_xray.ps .
cp ../qso_ec.ps .
cp ../f09.eps .
