//
// Code auto-generated by initpackage (XSPEC12 local model package 
// code generator).  Do not edit
// Package: clmass Created :
// Function body: clmassFunctionMap.cxx

#include    "clmassFunctionMap.h"

#include    <XSModelFunction.h>
#include <cstdio>
#include <iterator> 

void 
createclmassFunctionMap()
{


	XSFunctionMap["clmass"]   = new XSCall<XSMixCCall>(hydrostatic);
	XSFunctionMap["nfwmass"]  = new XSCall<XSMixCCall>(nfwhydrostatic);
	XSFunctionMap["monomass"] = new XSCall<XSMixCCall>(monohydrostatic);

}
