#!/bin/bash
ulimit -S -d 2048000

MOS1id=$1
tools=$2

cp evli_mos1.fits evli_mos1_old.fits

export SAS_CCF=../ccf.cif
export OUTSASDIR="./"

CCD=({01,02,03,04,05,06,07})

for k in 0 1 2 3 4 5 6; do {
  EXTNAME=BADPIX${CCD[${k}]}
  fextract infile=evli_mos1.fits"["${EXTNAME}"]" outfile=${EXTNAME}.fits clobber=yes
};
done

echo ""
echo "	cleaning additional bad pixels"

infile=${tools}/badpix_row_200.fits[BADPIX][#row==1]
# EXAMPLE: to flag pixels with coordinates 98,110 - 98,113 (4 pixels) in CCD 1:
#ftcopy $infile BADPIX.fits clobber=yes
#${tools}/write_badpix_row BADPIX.fits[BADPIX] 1 98 110 3 4 3
#${tools}/merge_BADPIX_extension BADPIX01.fits BADPIX.fits

echo ""
echo "	update badpix extentions and flag setting"

echo "" >> ${3}_MOS1_images.log 2>&1
echo "	update badpix extentions and flag setting" >> ${3}_MOS1_images.log 2>&1

ebadpixupdate eventset=evli_mos1.fits fromccf=N \
           badpixtables="BADPIX01.fits:BADPIX01 BADPIX02.fits:BADPIX02 \
	      BADPIX03.fits:BADPIX03 BADPIX04.fits:BADPIX04 \
	      BADPIX05.fits:BADPIX05 BADPIX06.fits:BADPIX06 \
	      BADPIX07.fits:BADPIX07" >> ${3}_MOS1_images.log 2>&1 

rm BADPIX*.fits

echo ""
echo "	clean MOS1 event file finished"

