#!/bin/bash

INFILE=$1
OUTFILE=$2
cp -f $INFILE test.fits

CCD=({7,6,11,2,11,5,5})
COL=({34,31,62,55,19,44,11})
COL_THRESH_XX=({400,600,250,450,250,250,600})

echo ""

for k in 0 1 2 3 4 5 6; do {
	echo "	cleaning CCD ${CCD[${k}]} column ${COL[${k}]} below column-threshold ${COL_THRESH_XX[${k}]}"
	fselect test.fits $OUTFILE "CCDNR != ${CCD[${k}]} .or. RAWX != ${COL[${k}]} .or. PI > ${COL_THRESH_XX[${k}]}  .or. PATTERN != 0" clobber=yes
	mv -f $OUTFILE test.fits

};
done

CCD=({1,10,10})
COL=({13,62,61})
COL_THRESH_XX=({250,300,300})

for k in 0 1 2; do {
	echo "	cleaning CCD ${CCD[${k}]} column ${COL[${k}]} below column-threshold ${COL_THRESH_XX[${k}]}"
	fselect test.fits $OUTFILE "CCDNR != ${CCD[${k}]} .or. RAWX != ${COL[${k}]} .or. PI > ${COL_THRESH_XX[${k}]}" clobber=yes

	mv -f $OUTFILE test.fits

};
done

mv -f test.fits $OUTFILE

